# file:   .travis.yml
# author: Jess Robertson
#         Minerals Resources National Research Flagship
# date:   Wednesday January 14, 2015

language: python
python:
    - "3.4"
    - "3.3"
    - "2.7"

# Command to install miniconda to build test environment
before_install:
  - sudo apt-get update -qq
  - wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Add Jess' binstar channel to get custom builds
  - conda config --add channels jesserobertson
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n test-pydym python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib h5py coverage coveralls
  - source activate test-pydym
  - python setup.py update_version install

# Command to run tests
script:
  - coverage run --source pydym run_test.py

after_success:
  - coveralls
